name: sharedllm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - grpcio
  - grpcio-tools
  - langchain
  - sentence-transformers
  - faiss-cpu
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - uvicorn
  - fastapi
  - pytest
  - black
  - isort
  - mypy
  - fastmcp