# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentence_transformer.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'sentence_transformer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asentence_transformer.proto\"!\n\rEncodeRequest\x12\x10\n\x08\x64ocument\x18\x01 \x01(\t\"#\n\x0e\x45ncodeResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x32\x44\n\x0fSentenceEncoder\x12\x31\n\x0e\x45ncodeDocument\x12\x0e.EncodeRequest\x1a\x0f.EncodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentence_transformer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODEREQUEST']._serialized_start=30
  _globals['_ENCODEREQUEST']._serialized_end=63
  _globals['_ENCODERESPONSE']._serialized_start=65
  _globals['_ENCODERESPONSE']._serialized_end=100
  _globals['_SENTENCEENCODER']._serialized_start=102
  _globals['_SENTENCEENCODER']._serialized_end=170
# @@protoc_insertion_point(module_scope)
